[build]
  publish   = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cheerio"]

[functions."scrape"]
  timeout = 30

[functions."order"]
  timeout = 15
